node {

    echo "Start Jenkins build process..."

    stage('Checkout') {
        echo  "Stage is Checkout"
	    checkout scm 
    }

    stage('Build') {
    	echo  "Stage is Build"
        bat 'dir src'
        bat 'buildit.bat'
        echo  "After build bat"
    }

    stage('Test') {
    	echo  "Stage is Test"
    	bat "testit.bat"
        echo  "After testit.bat"
    }

    echo "Jenkins build complete..."
  
}