node {

    echo "Start Jenkins build process..."

    stage('Checkout') {
        echo  "Stage is Checkout"
	checkout scm 
    }

    stage('Build') {
    	echo  "Stage is Build"
        dir
        echo  "After the dir command"
        cd src
        echo  "After cd src command"
    	javac TUCGrader.java
        echo  "After javac TUCGrader.java command"
    }

    stage('Test') {
    	echo  "Stage is Test"
        bat "dir"
        echo  "After the dir command"
    	//sh "cd src"
    	bat "java TUCGrader"
    }

    echo "Jenkins build complete..."
  
}