node {

    echo "Scripting Jenkins..."

    stage 'Stage is Checkout'
    echo  "Stage is Checkout"
    checkout scm 

    stage 'Stage is Build'
    echo  "Stage is Build"
    sh "cd src"
    sh "javac TUCGrader.java"

    stage 'Stage is Test'
    echo  "Stage is Test"
    //sh "cd src"
    sh "java TUCGrader"

    echo "Jenkins complete..."
  
}